### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by rankinstudio** [Jusas/astrometry-api-lite#4]
Thanks a lot for working on the fixes you've implemented so far. This is really a great project as an alternative to ansvr.

That said, is there a way similar to ansvr to have it only look at N number of stars extracted from the image? I can get a solve much faster by tweaking those settings with ansvr. If not, that'd be an awesome feature.

Cheers!

David

**Comment by Jusas** [comment]
You're right, I reviewed the solve-field arguments and there's the `--depth` arg that allows you to specify how many field objects to look at. I did a few tests and it does indeed shave off some solver time, and also that the image itself depends affects what outcome you get - for one image a parameter of 15 was blazingly fast, but for another it resulted in a field not solved - a value of 25 was suitable for that one. Obviously it depends on the number of artifacts in the image. I'm considering of adding this as an optional parameter, to be used with a little caution as in worst case it can result in images not solving at all when it can't find a satisfactory result with the limited number of field objects.

**Comment by rankinstudio** [comment]
Keeping ansvr running on windows 10 is getting more and more difficult. Constant reinstalls ect. Really the only difference I see between what you've done here and ansvr (performance wise) is the ability to chose the number of stars, and the noise reduction setting. On my setup, I choose a value of 5 for the noise reduction and then 35 for the stars to look at in ansvr, and I can shave my solves down to about 4 seconds with 100% solve rate.  I'd be super grateful if you implemented those two features with astrometry api lite. I do asteroid survey type work and bouncing between fields requires frequent accurate solves.  

Thanks again! 

David

**Comment by Jusas** [comment]
I'm in the process of implementing this; `--depth` and `--sigma`. I may also implement tweaking those values from the dashboard.

**Comment by rankinstudio** [comment]
It would be awesome to have them on the dashboard as most of the software doesn't support sending those options over. SGP, Kstars/Ekos ect. 

Cheers!

**Comment by Jusas** [comment]
This feature has now been implemented, and is present in the 1.2.0 release.

https://github.com/Jusas/astrometry-api-lite/releases/tag/v1.2.0

**Comment by rankinstudio** [comment]
Thank you!
