### ISSUE TITLE
Failure using on Ubuntu 18.04

### ISSUE THREAD

**Issue by mworion** [Jusas/astrometry-api-lite#6]
Hi Jussi,

I installed latest 1.2 version with script to Ubuntu18.04. Worked fine. I got latest astropy 2.0.6 installed -> great.

Server is running. When I start to solve an image, I get the following log entry and a not solved image.

Jun 20 21:34:37 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Checking for a work item...
Jun 20 21:34:38 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Checked out work item 3
Jun 20 21:34:38 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: calling: solve-field -D /tmp/astrometry-temp/3 -o 3 --wcs /tmp/astrometry-temp/3/wcs -S /tmp/astrometry-temp/3/solved -l 300 --no-plots --scale-units arcsecperpix --scale-low 0.6560705679862305 --scale-high 1.9682117039586915 --ra 315.5070083333334 --dec 67.88426555555556 --radius 2 --downsample 2 --crpix-center --temp-dir /tmp/astrometry-temp/3/solver-temp /tmp/astro-upload/4c9c1e66b63d1fc6703971a72299c852.fit
Jun 20 21:34:38 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Spawned pid 8343
Jun 20 21:34:38 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Reading input file 1 of 1: "/tmp/astro-upload/4c9c1e66b63d1fc6703971a72299c852.fit"...
Jun 20 21:34:38 ASTRO-MOUNT astrometry-api-lite[7796]: GET /api/submissions/3 200 13.110 ms
Jun 20 21:34:38 ASTRO-MOUNT astrometry-api-lite[7796]: GET /api/jobs/3 200 13.133 ms
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: ERROR: Image type not recognized: Unknown image type "["cannot open `/tmp/astro-upload/4c9c1e66b63d1fc6703971a72299c852.fit' (No such file or directory)"]"
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: augment-xylist.c:589:backtick Failed to run command: /usr/bin/python -m astrometry.util.image2pnm --infile /tmp/astro-upload/4c9c1e66b63d1fc6703971a72299c852.fit --uncompressed-outfile /tmp/astrometry-temp/3/solver-temp/tmp.uncompressed.4bYWT1 --outfile /tmp/astrometry-temp/3/solver-temp/tmp.ppm.LfNR0T --ppm --mydir /usr/bin/solve-field
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite-mgr[7830]:  ioutils.c:567:run_command_get_outputs Command failed: return value 255
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Child process exited with code 255
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Solve-field failed
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Job marked as failure, error information updated
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Cleaning up /tmp/astrometry-temp/3
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Worker exiting
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite-mgr[7830]: Active worker count: 3/4
Jun 20 21:34:39 ASTRO-MOUNT astrometry-api-lite[7796]: GET /api/jobs/3 200 11.976 ms

Michel

**Comment by Jusas** [comment]
Ok, the error message is pretty clear; `cannot open  /tmp/astro-upload/4c9c1e66b63d1fc6703971a72299c852.fit' (No such file or directory)`

Perhaps this is a configuration issue. If the API has saved the uploaded files to one directory and the worker tries to find them from another, this is what would happen.
Both the API and the worker have their own configuration files (`dist/api/configuration.json` and `dist/worker/configuration.json`). The path to uploaded files is defined in both as `queueFileUploadDir` - do they match in both files? If not, there's the problem.

**Comment by mworion** [comment]
Jussi,

good hint. This was the issue. I used the install script and got 2 config files in dist/api. one is configuration.json and one named configuration.local.json. The config of the directories of .local.json did not match. once entered the right directory, I got solving. Why is there a configuration.local.json ? I did not have that in the past ?

Michel

**Comment by Jusas** [comment]
The configuration.local.json has been there since the beginning, but I should really get rid of it. Originally it was there so that you could easily switch to use a different config by defining the AAPI_LITE_ENV environment variable but this is largely unnecessary and confusing. Also having multiple configuration files may be adding complexity unnecessarily. I'll add this to my todo-list to simplify the configuration.
